# Generated by Django 2.2.10 on 2020-11-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='polls',
            field=models.ManyToManyField(blank=True, null=True, to='polls.Poll', verbose_name='Выбранные опросы'),
        ),
    ]
