# Generated by Django 2.2.10 on 2020-11-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201118_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='options',
            field=models.ManyToManyField(blank=True, null=True, to='polls.Option', verbose_name='Выбранные варианты'),
        ),
    ]
